<?php
require_once __DIR__.'/globals.php';
require_once __DIR__.'/app/gestor_estipulante.php';
header('Cache-Control: no-store, private');
function ge_h($s): string { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }
function ge_date($s): string { return $s ? date('d/m/Y H:i', strtotime($s)) : 'Ainda não registrada'; }
try { $service=new GestorEstipulante($conn,(int)($_SESSION['id_usuario']??0)); }
catch (DomainException $e) { http_response_code(403); exit(ge_h($e->getMessage())); }
$id=max(0,(int)($_GET['caso']??0));$error='';
if ($_SERVER['REQUEST_METHOD']==='POST') {
    try {
        if (!csrf_is_valid(is_string($_POST['csrf']??null)?$_POST['csrf']:null)) { http_response_code(403); throw new DomainException('Sessão do formulário inválida. Recarregue a página.'); }
        $service->save($id,$_POST);
        $_SESSION['ge_message']='Registro salvo com sucesso.';
        header('Location: '.$BASE_URL.'gestor_estipulante.php?caso='.$id,true,303);exit;
    } catch (DomainException $e) { $error=$e->getMessage(); }
    catch (Throwable $e) { error_log('[GESTOR] '.$e->getMessage());$error='Não foi possível salvar. Seus dados permanecem no formulário; tente novamente.';http_response_code(500); }
}
$rows=$service->census();$selected=null;$active=[];
foreach ($rows as &$r) {
    $r['aberto']=$r['internado_int']==='s' && !$r['alta_em'];
    $end=$r['alta_em']?strtotime($r['alta_em']):(!$r['aberto'] && $r['alta_origem'] ? strtotime($r['alta_origem']) : time());
    $r['dias']=max(0,(int)floor(($end-strtotime($r['data_intern_int']))/86400));
    $r['sem_evolucao']=!$r['ultima_evolucao'] || strtotime($r['ultima_evolucao'])<time()-48*3600;
    if ($r['aberto']) $active[]=$r;
    if ((int)$r['id_internacao']===$id) $selected=$r;
} unset($r);
if ($id && !$selected) { http_response_code(404);exit('Caso não encontrado no seu escopo.'); }
$write=$service->canWrite() && (!$selected || $selected['aberto']);
$message=$_SESSION['ge_message']??'';unset($_SESSION['ge_message']);
$search=trim((string)($_GET['busca']??''));$filter=(string)($_GET['filtro']??'ativos');
$visible=array_filter($rows,static function($r)use($search,$filter){
    if ($search!=='' && stripos($r['nome_pac'].' '.$r['nome_hosp'].' '.$r['nome_est'],$search)===false) return false;
    if ($filter==='encerrados') return !$r['aberto'];
    if (!$r['aberto']) return false;
    if ($filter==='atrasadas') return (int)$r['tarefas_vencidas']>0;
    if ($filter==='sem_evolucao') return $r['sem_evolucao'];
    if ($filter==='sem_previsao') return !$r['previsao_alta'];
    return true;
});
function ge_hidden(string $action): void { echo '<input type="hidden" name="csrf" value="'.ge_h(csrf_token()).'"><input type="hidden" name="acao" value="'.ge_h($action).'">'; }
?>
<?php require_once __DIR__.'/templates/header.php'; ?>
<link rel="stylesheet" href="<?=ge_h($BASE_URL)?>css/gestor_estipulante.css?v=<?=filemtime(__DIR__.'/css/gestor_estipulante.css')?>">
<main class="ge-page container-fluid listagem-page">
<div class="listagem-hero listagem-hero--module listagem-hero--internacoes"><div class="listagem-hero__copy"><div class="listagem-kicker">Gestor estipulante · Acompanhamento assistencial</div><h1 class="listagem-title"><?=$selected?ge_h($selected['nome_pac']):'Gestão de casos clínicos'?></h1></div><div class="listagem-hero__actions"><span class="ge-profile"><?=$service->canWrite()?'Médico / Enfermeiro':'Gerente · Consulta'?></span><?php if($service->canWrite()):?><a class="btn listagem-btn-top listagem-btn-top--blue" href="<?=ge_h($BASE_URL)?>cad_internacao.php"><i class="bi bi-plus-circle"></i> Registrar internação</a><?php endif;?></div></div>
<?php if(!$selected):?><nav class="ge-shortcuts" aria-label="Módulos do gestor"><?php foreach(['Pacientes'=>'list_paciente.php','Hospitais'=>'list_hospital.php','Internações'=>'list_internacao.php','Censo hospitalar'=>'list_censo.php','BI'=>'bi_navegacao.php'] as $label=>$url):?><a href="<?=ge_h($BASE_URL.$url)?>"><?=ge_h($label)?> <span>→</span></a><?php endforeach;if($service->canWrite()):?><a href="<?=ge_h($BASE_URL)?>list_internacao_gerar_alta.php">Altas <span>→</span></a><?php endif;?></nav><?php endif;?>
<?php if($message):?><div class="notice success" role="status"><?=ge_h($message)?></div><?php endif;if($error):?><div class="notice error" role="alert"><?=ge_h($error)?></div><?php endif;?>
<?php if(!$selected): ?>
<section class="metrics"><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?filtro=ativos"><span>Casos em acompanhamento</span><strong><?=count($active)?></strong><small>No seu escopo de acesso</small></a><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?filtro=sem_evolucao"><span>Sem evolução há 48h</span><strong><?=count(array_filter($active,fn($r)=>$r['sem_evolucao']))?></strong><small>Inclui casos sem registro</small></a><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?filtro=atrasadas"><span>Tarefas vencidas</span><strong><?=array_sum(array_column($active,'tarefas_vencidas'))?></strong><small>Aguardando conclusão</small></a><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?filtro=sem_previsao"><span>Sem previsão de alta</span><strong><?=count(array_filter($active,fn($r)=>!$r['previsao_alta']))?></strong><small>Planejamento pendente</small></a><div><span>Permanência média atual</span><strong><?=count($active)?number_format(array_sum(array_column($active,'dias'))/count($active),1,',','.'): '—'?></strong><small>Dias dos casos em acompanhamento</small></div></section>
<section class="card"><div class="section-heading"><h2>Censo de internações</h2><span><?=count($visible)?> casos</span></div><form action="<?=ge_h($BASE_URL)?>gestor_estipulante.php" method="get" class="filters"><input name="busca" aria-label="Buscar paciente, hospital ou estipulante" placeholder="Buscar paciente, hospital ou estipulante" value="<?=ge_h($search)?>"><select name="filtro" aria-label="Filtrar casos"><?php foreach(['ativos'=>'Em acompanhamento','sem_evolucao'=>'Sem evolução há 48h','atrasadas'=>'Com tarefas vencidas','sem_previsao'=>'Sem previsão de alta','encerrados'=>'Encerrados'] as $key=>$label):?><option value="<?=$key?>" <?=$filter===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select><button>Filtrar</button></form>
<?php if(!$rows):?><div class="empty"><h3>Nenhuma internação disponível</h3><p>O censo exibe as internações já cadastradas no FullCare para os hospitais e estipulantes vinculados à sua conta.</p><p>Se o vínculo ainda não foi configurado, solicite ao administrador a definição do seu escopo.</p></div><?php elseif(!$visible):?><div class="empty">Nenhum caso corresponde aos filtros selecionados.</div><?php else:?><div class="table-wrap"><table><thead><tr><th>Paciente / estipulante</th><th>Hospital / acomodação</th><th>Permanência</th><th>Responsável</th><th>Última evolução</th><th>Previsão de alta</th><th>Atenção</th><th></th></tr></thead><tbody><?php foreach($visible as $r):?><tr><td><strong><?=ge_h($r['nome_pac'])?></strong><small><?=ge_h($r['nome_est']?:'Sem estipulante')?></small></td><td><?=ge_h($r['nome_hosp'])?><small><?=ge_h($r['acomodacao_int'])?></small></td><td><?=$r['dias']?> dias<small>Desde <?=ge_h(substr($r['data_intern_int'],0,10))?></small></td><td><?=ge_h($r['responsavel']?:'Não atribuído')?></td><td><?=ge_h(ge_date($r['ultima_evolucao']))?></td><td><?=ge_h($r['previsao_alta']?:'Não informada')?></td><td><?php if(!$r['aberto']):?><span class="tag">Encerrado</span><?php else: if($r['sem_evolucao']):?><span class="tag warn">Atualizar evolução</span><?php endif;if($r['tarefas_vencidas']):?><span class="tag danger"><?=(int)$r['tarefas_vencidas']?> vencidas</span><?php endif;endif;?></td><td><a class="open" href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=(int)$r['id_internacao']?>">Abrir →</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<p class="source">Fonte: internações cadastradas no FullCare. A cobertura depende da atualização do censo hospitalar. Última alteração na base dos hospitais exibidos: <?=ge_h(ge_date($rows?max(array_column($rows,'censo_atualizado')):null))?>.</p></section>
<?php else:
$team=$service->team($id);$evolutions=$service->records('ge_evolucao',$id);$tasks=$service->records('ge_pendencia',$id);$history=$service->records('ge_historico',$id);
$draft=[];$draftId=0;$parent=max(0,(int)($_GET['complemento']??0));
foreach($evolutions as $ev) if($ev['status']==='rascunho' && (int)$ev['id']===(int)($_GET['rascunho']??0) && (int)$ev['autor_id']===$service->user) { $draft=json_decode($ev['dados'],true)?:[];$draftId=(int)$ev['id'];$parent=(int)$ev['complemento_de']; }
if($error && ($_POST['acao']??'')==='evolucao') {$draft=$_POST;$draftId=(int)($_POST['evolucao_id']??0);$parent=(int)($_POST['complemento_de']??0);}
$plan=$error && ($_POST['acao']??'')==='plano'?$_POST:$selected;
?>
<a class="back" href="<?=ge_h($BASE_URL)?>gestor_estipulante.php">← Voltar ao censo</a>
<section class="card summary"><div><span>Hospital</span><strong><?=ge_h($selected['nome_hosp'])?></strong></div><div><span>Acomodação</span><strong><?=ge_h($selected['acomodacao_int'])?></strong></div><div><span>Admissão</span><strong><?=ge_h($selected['data_intern_int'])?></strong></div><div><span>Permanência</span><strong><?=$selected['dias']?> dias</strong></div><div><span>Situação</span><strong><?=$selected['aberto']?'Em acompanhamento':'Encerrado'?></strong></div></section>
<section class="card"><h2>Informações da admissão</h2><p><strong>Médico titular:</strong> <?=ge_h($selected['titular_int']?:'Não informado')?></p><p><strong>Estipulante:</strong> <?=ge_h($selected['nome_est']?:'Não informado')?></p><details><summary>Relato clínico de origem</summary><p><?=nl2br(ge_h($selected['rel_int']?:'Sem relato registrado na internação.'))?></p></details></section>
<div class="tabs"><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>#plano">Plano do caso</a><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>#evolucao">Evolução clínica</a><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>#pendencias">Pendências</a><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>#historico">Histórico</a></div>
<section class="card" id="plano"><h2>Plano do caso e preparação para alta</h2><form action="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>" method="post"><?php ge_hidden('plano');?><input type="hidden" name="versao" value="<?=(int)($plan['versao']??0)?>"><fieldset <?=$write?'':'disabled'?>><div class="grid"><label>Responsável pelo caso<select name="responsavel_id"><option value="">Não atribuído</option><?php foreach($team as $u):?><option value="<?=(int)$u['id_usuario']?>" <?=(int)($plan['responsavel_id']??0)===(int)$u['id_usuario']?'selected':''?>><?=ge_h($u['usuario_user'])?></option><?php endforeach;?></select></label><label>Previsão de alta<input type="date" name="previsao_alta" value="<?=ge_h($plan['previsao_alta']??'')?>"></label><label>Barreiras para alta<textarea name="barreiras" maxlength="10000"><?=ge_h($plan['barreiras']??'')?></textarea></label><label>Plano de alta e continuidade do cuidado<textarea name="plano_alta" maxlength="10000"><?=ge_h($plan['plano_alta']??'')?></textarea></label></div><?php if($write):?><button>Salvar plano do caso</button><?php endif;?></fieldset></form></section>
<section class="card" id="evolucao"><h2>Evolução clínica</h2><?php if($write):?><p>Registre a avaliação e a origem das informações. Após finalizar, alterações são feitas por complemento.</p><form action="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>" method="post"><?php ge_hidden('evolucao');?><input type="hidden" name="evolucao_id" value="<?=$draftId?>"><input type="hidden" name="complemento_de" value="<?=$parent?>"><?php if($parent):?><div class="notice">Complemento da evolução #<?=$parent?></div><?php endif;?><div class="grid"><?php foreach(GestorEstipulante::FIELDS as $key=>$label):?><label><?=$label?><?=in_array($key,['origem','situacao','plano'])?' *':''?><textarea name="<?=$key?>" maxlength="10000" rows="3"><?=ge_h($draft[$key]??'')?></textarea></label><?php endforeach;?></div><div class="actions"><button name="status" value="finalizada">Finalizar evolução</button><button class="secondary" name="status" value="rascunho">Salvar rascunho</button></div><small>* Obrigatório ao finalizar.</small></form><?php endif;?>
<h3>Linha do tempo</h3><?php if(!$evolutions):?><p class="muted">Nenhuma evolução registrada.</p><?php endif;foreach($evolutions as $ev):?><details class="timeline"><summary><strong><?=$ev['status']==='finalizada'?'Evolução finalizada':'Rascunho'?> #<?=(int)$ev['id']?></strong> · <?=ge_h($ev['autor'])?> · <?=ge_h(ge_date($ev['finalizado_em']?:$ev['criado_em']))?></summary><?php if($ev['complemento_de']):?><p>Complementa a evolução #<?=(int)$ev['complemento_de']?></p><?php endif;foreach(json_decode($ev['dados'],true)?:[] as $key=>$value):if($value==='')continue;?><div class="clinical"><strong><?=ge_h(GestorEstipulante::FIELDS[$key]??$key)?></strong><p><?=nl2br(ge_h($value))?></p></div><?php endforeach;if($write):?><a href="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>&<?=$ev['status']==='finalizada'?'complemento':'rascunho'?>=<?=(int)$ev['id']?>#evolucao"><?=$ev['status']==='finalizada'?'Adicionar complemento':'Continuar rascunho'?></a><?php endif;?></details><?php endforeach;?></section>
<section class="card" id="pendencias"><h2>Pendências e próximos passos</h2><?php if($write):$taskInput=$error&&($_POST['acao']??'')==='pendencia'?$_POST:[];?><form action="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>" method="post"><?php ge_hidden('pendencia');?><label>O que precisa ser feito?<textarea name="descricao" maxlength="3000" required><?=ge_h($taskInput['descricao']??'')?></textarea></label><div class="grid"><label>Responsável<select name="responsavel_id" required><?php foreach($team as $u):?><option value="<?=(int)$u['id_usuario']?>" <?=(int)($taskInput['responsavel_id']??$service->user)===(int)$u['id_usuario']?'selected':''?>><?=ge_h($u['usuario_user'])?></option><?php endforeach;?></select></label><label>Prazo<input type="datetime-local" name="prazo" required value="<?=ge_h($taskInput['prazo']??'')?>"></label></div><button>Adicionar pendência</button></form><?php endif;?>
<?php if(!$tasks):?><p class="muted">Nenhuma pendência registrada.</p><?php endif;foreach($tasks as $t):?><article class="task"><div><strong><?=ge_h($t['descricao'])?></strong><small><?=ge_h($t['autor'])?> · Prazo <?=ge_h(ge_date($t['prazo']))?></small><span class="tag <?=$t['concluido_em']?'':(strtotime($t['prazo'])<time()?'danger':'warn')?>"><?=$t['concluido_em']?'Concluída':(strtotime($t['prazo'])<time()?'Vencida':'Em aberto')?></span></div><?php if($write&&!$t['concluido_em']):?><form action="<?=ge_h($BASE_URL)?>gestor_estipulante.php?caso=<?=$id?>" method="post"><?php ge_hidden('concluir');?><input type="hidden" name="pendencia_id" value="<?=(int)$t['id']?>"><button class="secondary">Concluir</button></form><?php endif;?></article><?php endforeach;?></section>
<section class="card"><h2>Alta hospitalar</h2><?php if($selected['alta_origem']):?><p>Alta registrada no FullCare em <?=ge_h(ge_date($selected['alta_origem']))?>.</p><?php elseif($write):?><p>Utilize o registro de altas do FullCare para atualizar a internação e o censo.</p><a class="open" href="<?=ge_h($BASE_URL)?>list_internacao_gerar_alta.php?pesquisa_pac=<?=rawurlencode($selected['nome_pac'])?>">Registrar alta hospitalar</a><?php else:?><p>Consulta do encerramento registrado pela equipe assistencial.</p><?php endif;?></section>
<section class="card" id="historico"><h2>Histórico de ações</h2><?php foreach($history as $event):?><p><?=ge_h(ge_date($event['criado_em']))?> · <strong><?=ge_h($event['autor'])?></strong> · <?=ge_h(['plano'=>'Plano atualizado','evolucao'=>'Evolução registrada','pendencia'=>'Pendência criada','concluir'=>'Pendência concluída','alta'=>'Alta registrada'][$event['acao']]??$event['acao'])?></p><?php endforeach;if(!$history):?><p class="muted">Nenhuma ação registrada.</p><?php endif;?></section>
<?php endif;?>
</main><?php require_once __DIR__.'/templates/footer.php'; ?>
