CREATE TABLE IF NOT EXISTS tb_hc_plano (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 internacao_id INT NOT NULL,
 solicitacao_id BIGINT UNSIGNED NULL,
 inicio DATE NOT NULL,
 fim DATE NOT NULL,
 fornecedor VARCHAR(120) NOT NULL,
 modalidade VARCHAR(60) NOT NULL,
 plano TEXT NOT NULL,
 equipe TEXT NOT NULL,
 materiais TEXT NOT NULL,
 equipamentos TEXT NOT NULL,
 autorizacao VARCHAR(100) NOT NULL,
 criado_por INT NOT NULL,
 criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_hc_plano_solicitacao (solicitacao_id),
 KEY idx_hc_plano_caso (internacao_id, fim)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS tb_hc_prorrogacao (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 plano_id BIGINT UNSIGNED NOT NULL,
 inicio DATE NOT NULL,
 fim DATE NOT NULL,
 fornecedor VARCHAR(120) NOT NULL,
 modalidade VARCHAR(60) NOT NULL,
 plano TEXT NOT NULL,
 equipe TEXT NOT NULL,
 materiais TEXT NOT NULL,
 equipamentos TEXT NOT NULL,
 justificativa TEXT NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'pendente',
 parecer TEXT NULL,
 solicitado_por INT NOT NULL,
 solicitado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 decidido_por INT NULL,
 decidido_em DATETIME NULL,
 versao INT NOT NULL DEFAULT 1,
 CONSTRAINT fk_hc_prorrogacao_plano FOREIGN KEY (plano_id) REFERENCES tb_hc_plano(id),
 KEY idx_hc_prorrogacao_status (status, plano_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
